export const data = () => {
    return [{
        "idDrink": "17222",
        "strDrink": "A1",
        "strCategory": "Cocktail",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.",
        "strInstructionsDE": "Alle Zutaten in einen Cocktailshaker geben, mischen und über Eis in ein gekühltes Glas servieren.",
        "strInstructionsIT": "Versare tutti gli ingredienti in uno shaker, mescolare e servire con ghiaccio in un bicchiere freddo.",
        "strDrinkThumb": "https://i.pinimg.com/564x/57/0a/f7/570af7f95de2ed85f6c52ea3990404c5.jpg",
        "strIngredient1": "Gin",
        "strIngredient2": "Grand Marnier",
        "strIngredient3": "Lemon Juice",
        "strIngredient4": "Grenadine",
        "strMeasure1": "1 3/4 shot ",
        "strMeasure2": "1 Shot ",
        "strMeasure3": "1/4 Shot",
        "strMeasure4": "1/8 Shot",
        "strCreativeCommonsConfirmed": "No",
        "dateModified": "2017-09-07 21:42:09"
    },
    {
        "idDrink": "13501",
        "strDrink": "ABC",
        "strCategory": "Shot",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Shot glass",
        "strInstructions": "Layered in a shot glass.",
        "strInstructionsDE": "Schichtaufbau in einem Schnapsglas.",
        "strInstructionsIT": "Versa in ordine di lettera i vari ingredienti. 1/3 del bicchiere va riempito con l'Amaretto, 1/3 di Baileys e il restante di Cognac.",
        "strDrinkThumb": "https://www.acouplecooks.com/wp-content/uploads/2021/03/B52-Shot-Cocktail-009.jpg",
        "strIngredient1": "Amaretto",
        "strIngredient2": "Baileys irish cream",
        "strIngredient3": "Cognac",
        "strMeasure1": "1/3 ",
        "strMeasure2": "1/3 ",
        "strMeasure3": "1/3 ",
        "strCreativeCommonsConfirmed": "No",
        "dateModified": "2016-08-31 19:32:08"
    },
    {
        "idDrink": "17225",
        "strDrink": "Ace",
        "strCategory": "Cocktail",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Martini Glass",
        "strInstructions": "Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.",
        "strInstructionsDE": "Alle Zutaten in einem Cocktailshaker mit Eis schütteln und dann in einem kalten Glas abseihen.",
        "strInstructionsIT": "Shakerare tutti gli ingredienti in uno shaker e ghiaccio, quindi filtrare in un bicchiere freddo.",
        "strDrinkThumb": "https://www.acouplecooks.com/wp-content/uploads/2020/05/Clover-Club-Cocktail-006.jpg",
        "strIngredient1": "Gin",
        "strIngredient2": "Grenadine",
        "strIngredient3": "Heavy cream",
        "strIngredient4": "Milk",
        "strIngredient5": "Egg White",
        "strMeasure1": "2 shots ",
        "strMeasure2": "1/2 shot ",
        "strMeasure3": "1/2 shot ",
        "strMeasure4": "1/2 shot",
        "strMeasure5": "1/2 Fresh",
        "strCreativeCommonsConfirmed": "No",
        "dateModified": "2017-09-07 22:05:06"
    },
    {
        "idDrink": "17837",
        "strDrink": "Adam",
        "strTags": "Alcoholic,Holiday",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.",
        "strInstructionsDE": "In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.",
        "strInstructionsIT": "In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.",
        "strDrinkThumb": "https://www.moodymixologist.com/wp-content/uploads/2021/05/IMG_5332-2950885.jpg",
        "strIngredient1": "Dark rum",
        "strIngredient2": "Lemon juice",
        "strIngredient3": "Grenadine",
        "strMeasure1": "2 oz ",
        "strMeasure2": "1 oz ",
        "strMeasure3": "1 tsp ",
        "strCreativeCommonsConfirmed": "Yes",
        "dateModified": "2016-09-02 11:29:29"
    },
    {
        "idDrink": "13938",
        "strDrink": "AT&T",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Highball Glass",
        "strInstructions": "Pour Vodka and Gin over ice, add Tonic and Stir",
        "strInstructionsDE": "Wodka und Gin über das Eis gießen, Tonic hinzufügen und umrühren.",
        "strInstructionsIT": "Versare la vodka e il gin sul ghiaccio, aggiungere l'acqua tonica e mescolare",
        "strDrinkThumb": "https://thumbs.dreamstime.com/b/club-soda-gin-vodka-tonic-black-background-12849282.jpg",
        "strIngredient1": "Absolut Vodka",
        "strIngredient2": "Gin",
        "strIngredient3": "Tonic water",
        "strMeasure1": "1 oz ",
        "strMeasure2": "1 oz ",
        "strMeasure3": "4 oz ",
        "strCreativeCommonsConfirmed": "No",
        "dateModified": "2017-04-24 22:00:19"
    },
    {
        "idDrink": "14610",
        "strDrink": "ACID",
        "strCategory": "Shot",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Shot glass",
        "strInstructions": "Poor in the 151 first followed by the 101 served with a Coke or Dr Pepper chaser.",
        "strInstructionsDE": "Gering den 151 gefolgt von der 101, die mit einer Cola oder Dr. Pepper Chaser serviert wird.",
        "strInstructionsIT": "Versa prima il Bacardi 151 seguito dal 101, servito con una Coca-Cola.",
        "strDrinkThumb": "https://www.easy-cocktail-recipes.net/wp-content/uploads/2019/10/59.jpg",
        "strIngredient1": "151 proof rum",
        "strIngredient2": "Wild Turkey",
        "strMeasure1": "1 oz Bacardi ",
        "strMeasure2": "1 oz ",
        "strCreativeCommonsConfirmed": "No",
        "dateModified": "2016-11-15 11:28:37"
    },
    {
        "idDrink": "17833",
        "strDrink": "A. J.",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Shake ingredients with ice, strain into a cocktail glass, and serve.",
        "strInstructionsIT": "Shakerare gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.",
        "strDrinkThumb": "https://data.thefeedfeed.com/recommended/15233855655acd04dd43d53.jpg",
        "strIngredient1": "Applejack",
        "strIngredient2": "Grapefruit juice",
        "strMeasure1": "1 1/2 oz ",
        "strMeasure2": "1 oz ",
        "strCreativeCommonsConfirmed": "Yes",
        "dateModified": "2016-09-02 11:16:58"
    },
    {
        "idDrink": "12764",
        "strDrink": "Karsk",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Highball glass",
        "strInstructions": "Put a copper coin in a coffe-cup and fill up with coffee until you no longer see the coin, then add alcohol until you see the coin. Norwegian speciality.",
        "strInstructionsDE": "Legen Sie eine Kupfermünze in eine Kaffeetasse und füllen Sie sie mit Kaffee, bis Sie die Münze nicht mehr sehen, dann fügen Sie Alkohol hinzu, bis Sie die Münze wieder sehen. Norwegische Spezialität.",
        "strInstructionsIT": "Metti una moneta di rame in una tazza da caffè e riempila di caffè finché non vedi più la moneta, quindi aggiungi l'alcol finché non vedi la moneta. Specialità norvegese.",
        "strDrinkThumb": "https://i.pinimg.com/564x/f8/ad/b1/f8adb1dffd0c001f8627afc9c2d043d3.jpg",
        "strIngredient1": "Coffee",
        "strIngredient2": "Grain alcohol",
        "strMeasure1": "1 part ",
        "strMeasure2": "2 parts ",
        "strCreativeCommonsConfirmed": "No",
        "dateModified": "2017-02-20 14:54:31"
    },
    {
        "idDrink": "12776",
        "strDrink": "Melya",
        "strCategory": "Coffee / Tea",
        "strAlcoholic": "Non alcoholic",
        "strGlass": "Coffee mug",
        "strInstructions": "Brew espresso. In a coffee mug, place 1 teaspoon of unsweetened powdered cocoa, then cover a teaspoon with honey and drizzle it into the cup. Stir while the coffee brews, this is the fun part. The cocoa seems to coat the honey without mixing, so you get a dusty, sticky mass that looks as though it will never mix. Then all at once, presto! It looks like dark chocolate sauce. Pour hot espresso over the honey, stirring to dissolve. Serve with cream.",
        "strInstructionsDE": "Espresso zubereiten. In eine Kaffeetasse 1 Teelöffel ungesüßten, pulverisierten Kakao geben, dann einen Teelöffel Honig in die Tasse träufeln. Rühren Sie um, während der Kaffee brüht, das ist der lustige Teil. Der Kakao scheint den Honig ohne Mischen zu überziehen, so dass Sie eine dichte, klebrige Masse erhalten, die aussieht, als würde sie sich nie vermischen. Dann auf einmal, presto! Es sieht aus wie dunkle Schokoladensoße. Heißen Espresso über den Honig gießen und unter Rühren auflösen. Mit Sahne servieren.",
        "strInstructionsIT": "Prepara l'espresso.\r\nIn una tazza da caffè, mettete 1 cucchiaino di cacao amaro in polvere, quindi coprite un cucchiaino con del miele e versatelo nella tazza.\r\nMescola mentre il caffè si prepara, questa è la parte divertente.\r\nIl cacao sembra ricoprire il miele senza mescolarsi, quindi si ottiene una massa polverosa e appiccicosa che sembra non si mescolerà mai.\r\nVersare l'espresso caldo sul miele, mescolando per scioglierlo.\r\nServire con la panna.",
        "strDrinkThumb": "https://www.teahub.io/photos/full/116-1168254_coffee-cappuccino-espresso-beverage-cup-hot-morning-coffee.jpg",
        "strIngredient1": "Espresso",
        "strIngredient2": "Honey",
        "strIngredient3": "Cocoa powder",
        "strMeasure2": "Unsweetened &q...